## Use C-a instead of C-b as the prefix
#set -g prefix C-a
#unbind-key C-b
#bind-key C-a send-prefix


# Plugins
set -g @plugin 'dracula/tmux'

# be more responsive, changing the default delay
set -sg escape-time 1


# use UTF8
#set -g utf8
#set-window-option -g utf8 on

# make tmux display things in 256 colors
set -g default-terminal "screen-256color"

# re-enumera ventanas cuando se cierra una
set -g renumber-windows on

#recarga la configuracion de tmux y muestra un mensaje de confirmacion
bind r source-file ~/.tmux.conf \; display "~/.tmux.conf recargado!"

# Habilitar soporte de mouse
set -g mouse on


# Limite del historial
set -g history-limit 30000

# Tiempo en que se muestran2los mensages
set-option -g display-time 2000

# Habilitar teclas VI
set-window-option -g mode-keys vi

# Seleccionar texto tipo VIM
#bind-key -t vi-copy 'v' begin-selection
#bind y copy-pipe "xclip -in -selection clipboard"
bind y run "tmux show-buffer | xclip -i -selection clipboard"



# Copiar texto tipo VIM y guardarlo en portapapeles
#bind-key -t vi-copy 'y' copy-selection
#bind -t vi-copy y copy-pipe "xclip -in -selection clipboard"

# Mover las ventanas izquierda o derecha en la sesión
bind-key -n S-right next
bind-key -n S-left prev
bind-key -n S-down new-window -c "#{pane_current_path}"

# map Vi movement keys as pane movement keys
bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

# mover a otro panel con control y tecla de direccion
bind-key -n C-left	select-pane -L 
bind-key -n C-right  select-pane -R
bind-key -n C-up     select-pane -U
bind-key -n C-down   select-pane -D


# Cambiar tamaños del panel
bind-key -n C-S-left resize-pane -L 5
bind-key -n C-S-right resize-pane -R 5
bind-key -n C-S-up resize-pane -U 5
bind-key -n C-S-down resize-pane -D 5

# visual notification of activity in other windows
setw -g monitor-activity on
set -g visual-activity on

# active window title colors
#set-window-option -g window-status-current-fg colour166 #orange
#set-window-option -g window-status-current-bg default

# Highlight active window
#set-window-option -g window-status-current-bg white

## Barra de estado
set -g status on
# set-option -g status-utf8 on
set-option -g status-justify right
# set-option -g status-bg black
# set-option -g status-fg colour10
#set-option -g status-interval 5
#set-option -g status-left-length 30
#set-option -g status-left '#[fg=magenta]» #[fg=blue,bold]#T#[default]'
#set-option -g status-right '#[fg=cyan]»» #[fg=blue,bold] #[fg=magenta]%D %k:%M#[default]'
set-option -g visual-activity on
# set-window-option -g monitor-activity on
#set-window-option -g window-status-current-fg green
set-window-option -g clock-mode-colour green
set-window-option -g clock-mode-style 12

# Dracula plugin
# set -g @dracula-show-powerline true
# set -g @dracula-show-flags true
# for left
# set -g @dracula-show-left-sep 


# for right symbol (can set any symbol you like as separator)
# set -g @dracula-show-right-sep 

# it can accept `hostname` (full hostname), `session`, `shortname` (short name), `smiley`, `window`, or any character. 
set -g @dracula-show-left-icon 

# default is ✓. Avoid using non unicode characters that bash uses like $, * and !
set -g @dracula-git-show-current-symbol ✓


# set -g @dracula-border-contrast true

# available plugins: battery, cpu-usage, git, gpu-usage, ram-usage, tmux-ram-usage, network, network-bandwidth, network-ping, ssh-session, attached-clients, network-vpn, weather, time, mpc, spotify-tui, kubernetes-context, synchronize-panes
set -g @dracula-plugins "cpu-usage ram-usage"
# available colors: white, gray, dark_gray, light_purple, dark_purple, cyan, green, orange, red, pink, yellow
# set -g @dracula-[plugin-name]-colors "[background] [foreground]"
set -g @dracula-cpu-usage-colors "green dark_gray"


run '~/.tmux/plugins/tpm/tpm'
